# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

    # Use azure government
    - name: Use AzureUSGovernment
      run: az cloud set --name AzureUSGovernment

    # Login to azure
    - name: Login Azure
      run: az login --service-principal -u ${{secrets.AZURE_SP_ID}} -p ${{secrets.AZURE_SP_SECRET}} --tenant ${{secrets.AZURE_SP_TENANT}}

    # Set azure subscription
    - name: Set Azure Subscription
      run: az account set --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

    #   # Deploy Bicep file
    # - name: deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ./azuredeploy.bicep
    #     parameters: storagePrefix=mystore
    #     failOnStdErr: false